[2022-12-12 12:58:07,539] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rates.create_dataframe manual__2022-12-12T12:58:05.401615+00:00 [queued]>
[2022-12-12 12:58:07,545] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rates.create_dataframe manual__2022-12-12T12:58:05.401615+00:00 [queued]>
[2022-12-12 12:58:07,545] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 12:58:07,545] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 12:58:07,545] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 12:58:07,554] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): create_dataframe> on 2022-12-12 12:58:05.401615+00:00
[2022-12-12 12:58:07,560] {standard_task_runner.py:52} INFO - Started process 3862 to run task
[2022-12-12 12:58:07,562] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_rates', 'create_dataframe', 'manual__2022-12-12T12:58:05.401615+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/load_rates.py', '--cfg-path', '/tmp/tmpqfgif913', '--error-file', '/tmp/tmp0by0cu80']
[2022-12-12 12:58:07,563] {standard_task_runner.py:80} INFO - Job 17: Subtask create_dataframe
[2022-12-12 12:58:07,603] {task_command.py:369} INFO - Running <TaskInstance: load_rates.create_dataframe manual__2022-12-12T12:58:05.401615+00:00 [running]> on host 58259600a754
[2022-12-12 12:58:07,682] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_rates
AIRFLOW_CTX_TASK_ID=create_dataframe
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T12:58:05.401615+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T12:58:05.401615+00:00
[2022-12-12 12:58:07,700] {python.py:173} INFO - Done. Returned value was:         AED         AFN         ALL  ...           ZMK        ZMW         ZWL
0  4.176782  117.979297  121.277018  ...  10235.677475  18.948740  366.160363
0  4.176782  117.979297  121.277018  ...  10235.677475  18.948740  366.160363
0  4.177235  117.993578  121.292102  ...  10236.956907  18.951110  366.206170
0  4.150540  117.235943  120.060423  ...  10171.194552  18.841523  363.853655
0  4.144514  118.362513  119.463303  ...  10156.445865  18.864138  363.326122
0  4.155551  119.074390  120.943795  ...  10183.461167  18.973170  364.293086

[6 rows x 168 columns]
[2022-12-12 12:58:07,759] {xcom.py:585} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-12-12 12:58:07,760] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2380, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 197, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 582, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2022-12-12 12:58:07,769] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=load_rates, task_id=create_dataframe, execution_date=20221212T125805, start_date=20221212T125807, end_date=20221212T125807
[2022-12-12 12:58:07,778] {standard_task_runner.py:97} ERROR - Failed to execute job 17 for task create_dataframe (Object of type DataFrame is not JSON serializable; 3862)
[2022-12-12 12:58:07,814] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-12 12:58:07,850] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
